/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-09-20

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "tm_stm32f4_dac_signal.h"
#include "stm32f4xx_dac.h"
#include "tm_stm32f4_disco.h"
#include "tm_stm32f4_adc.h"
#include "tm_stm32f4_usb_vcp.h"
#include "tm_stm32f4_dma.h"
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */
uint16_t ADC_Value;
uint8_t bytes[2];
uint8_t i ;
uint8_t j = 0;
uint32_t num_samples = 2243;



/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void) {
    uint8_t c;
    /* System Init */
    SystemInit();
    TM_USB_VCP_Init();
    RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_ADC1, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_DAC, ENABLE);
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_DMA1 | RCC_AHB1Periph_DMA2, ENABLE);
	RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM6, ENABLE);


	GPIO_InitTypeDef      GPIO_InitStructure;
	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_0;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AN;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL ;
	GPIO_Init(GPIOA, &GPIO_InitStructure);

	NVIC_InitTypeDef NVIC_InitStruct;

	NVIC_InitStruct.NVIC_IRQChannel = ADC_IRQn;
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 1;
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0;
	NVIC_Init(&NVIC_InitStruct);

	ADC_ITConfig(ADC1, ADC_IT_EOC, ENABLE);

	ADC_InitTypeDef       ADC_InitStructure;
	ADC_InitStructure.ADC_Resolution = ADC_Resolution_12b;
	ADC_InitStructure.ADC_ScanConvMode = DISABLE;
	ADC_InitStructure.ADC_ContinuousConvMode = ENABLE;
	ADC_InitStructure.ADC_ExternalTrigConv = DISABLE;
	ADC_InitStructure.ADC_ExternalTrigConvEdge = ADC_ExternalTrigConvEdge_None;
	ADC_InitStructure.ADC_DataAlign = ADC_DataAlign_Right;
	ADC_InitStructure.ADC_NbrOfConversion = 1;
	ADC_Init(ADC1, &ADC_InitStructure);

	ADC_CommonInitTypeDef ADC_CommonInitStructure;
	ADC_CommonInitStructure.ADC_Mode = ADC_Mode_Independent;
	ADC_CommonInitStructure.ADC_Prescaler = ADC_Prescaler_Div6;
	ADC_CommonInitStructure.ADC_DMAAccessMode = ADC_DMAAccessMode_Disabled;
	ADC_CommonInitStructure.ADC_TwoSamplingDelay = ADC_TwoSamplingDelay_5Cycles;
	ADC_CommonInit(&ADC_CommonInitStructure);
	ADC_RegularChannelConfig(ADC1, ADC_Channel_0, 1, ADC_SampleTime_144Cycles);


    while (1){
	/* USB configured OK, drivers OK */

		if (TM_USB_VCP_Getc(&c) == TM_USB_VCP_DATA_OK)
		{
			ADC_Cmd (ADC1, ENABLE);
			counter = 0;
			i = 0;
			TM_DAC_SIGNAL_Init(TM_DAC1, TIM4);
			TM_DAC_SIGNAL_SetSignal(TM_DAC1, TM_DAC_SIGNAL_Signal_Sinus, 192000);
			TM_DMA_EnableInterrupts(DAC_SIGNAL_DMA_DAC1_STREAM);
			ADC_SoftwareStartConv(ADC1);
		}





}
}

void ADC_IRQHandler(void){
	ADC_ClearITPendingBit(ADC1, ADC_IT_EOC);
	if (i == num_samples){
			TM_USB_VCP_Puts("\n");
			ADC_Cmd (ADC1, DISABLE);
			//start = 0;
		}
	else {
		ADC_Value = ADC_GetConversionValue(ADC1);
		bytes[0] = ADC_Value >> 8;     // high byte
		bytes[1] = ADC_Value & 0x00FF; // low byte
		TM_USB_VCP_Send(bytes,2);
		i++;
	}
}

void TM_DMA_TransferCompleteHandler(DMA_Stream_TypeDef* DMA_Stream){
	counter++;
	if (counter>20){
		DAC_DeInit();
	}
}


